version: '2'

services:

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
     - "1080:80"
    environment:
     - PMA_ARBITRARY=1
     - PMA_HOST=mariadb
     - PMA_USER=root
     - PMA_PASSWORD=my-secret-pw
    volumes:
     - ./volumes/phpmyadmin:/sessions
     
  mariadb:
    image: mariadb
    environment:
     - MYSQL_ROOT_PASSWORD=my-secret-pw
    volumes:
     - ./volumes/mariadb:/var/lib/mysql
