version: '2'

services:

  web:
    image: wordpress
    ports:
     - 1980:80
    environment:
     - WORDPRESS_DB_HOST=db
     - WORDPRESS_DB_PASSWORD=uordpresRetete

  db:
    image: mariadb
    environment:
     - MYSQL_ROOT_PASSWORD=uordpresRetete
    volumes:
     - ./volumes/mariadb:/var/lib/mysql
